import Link from "next/link";
import { categories } from "@/lib/categories";
import { getAllPosts } from "@/lib/posts";
import { PostCard } from "@/components/post-card";
import { siteConfig } from "@/site.config";
export default function Home() { const posts = getAllPosts(); const featured = posts.filter((post) => post.featured).slice(0, 5); const experience = posts.filter((post) => post.experience).slice(0, 4); const services = [{label:"note",href:siteConfig.links.note},{label:"Brain",href:siteConfig.links.brain},{label:"BOOTH",href:siteConfig.links.booth},{label:"Gumroad",href:siteConfig.links.gumroad},{label:"楽天ROOM",href:siteConfig.links.rakutenRoom}].filter((s) => s.href);
 return <><section className="hero"><div className="shell"><p className="eyebrow">副業の実践記録</p><h1>{siteConfig.name}</h1><p className="hero-copy">AI・物販・SNS・デジタル販売。<br/>40代から実際に試している副業を、成功も失敗もそのまま記録しています。</p><div className="actions"><Link className="button" href="/about">はじめての方へ</Link><Link className="button button-secondary" href="/posts">最新の記事を見る</Link></div></div></section>
 <section className="section shell intro"><p className="eyebrow">このブログについて</p><h2>挑戦の途中を、飾らず残す。</h2><p>AI活用、物販、SNS、デジタル販売。実際にやってみた過程と、次に改善したいことを記録するブログです。</p><div className="inline-links"><Link href="/about">ブログについて →</Link><Link href="/profile">プロフィール →</Link></div></section>
 <section className="section tinted"><div className="shell"><div className="section-head"><div><p className="eyebrow">はじめての方へ</p><h2>まず読んでほしい記事</h2></div><Link href="/posts">すべて見る →</Link></div><div className="post-grid">{featured.map((post) => <PostCard key={post.slug} post={post}/>)}</div></div></section>
 <section className="section shell"><p className="eyebrow">カテゴリー</p><h2>カテゴリーから探す</h2><div className="category-grid">{categories.map((category) => <Link href={`/categories/${category.slug}`} className="category-card" key={category.slug}><h3>{category.name}</h3><p>{category.description}</p><span>記事を見る →</span></Link>)}</div></section>
 <section className="section tinted"><div className="shell"><div className="section-head"><div><p className="eyebrow">最新の記録</p><h2>最新の副業記録</h2></div><Link href="/posts">記事一覧へ →</Link></div><div className="post-grid">{posts.slice(0, 9).map((post) => <PostCard key={post.slug} post={post}/>)}</div></div></section>
 <section className="section shell"><p className="eyebrow">実践・体験記録</p><h2>実際にやってみた</h2><p className="lead">AI、Threads、BOOTH、物販。小さく試した実践と体験の記録です。</p><div className="post-grid">{experience.map((post) => <PostCard key={post.slug} post={post}/>)}</div></section>
 <section className="section shell cta"><p className="eyebrow">おすすめ・商品</p><h2>おすすめ・商品</h2><p>note、Brain、BOOTH、Gumroad、楽天ROOMなどへの案内をここに掲載できます。リンクを設定すると表示されます。</p>{services.length ? <div className="inline-links">{services.map((s) => <a href={s.href} key={s.label}>{s.label} →</a>)}</div> : <Link href="/recommendations" className="text-link">おすすめ・商品ページを見る →</Link>}</section></>; }
